### PR TITLE
set_info refactor, move download_images

### LINKED ISSUE #39: Refactor set_info file to match MTGJSON
Some of the fields in MTGJSON contain the same values that set_info carries, but have different names.

MTGJSON:
```
name: "Amonkhet",
code: "AKH",
releaseDate: "2017-04-28",
border: "black",
block: "Amonkhet",
type: "expansion",
booster: [
[
"rare",
"mythic rare"
],
"uncommon",
"uncommon",
"uncommon",
"common",
"common",
"common",
"common",
"common",
"common",
"common",
"common",
"common",
"common",
"land",
"marketing"
],
```

set_info:
```
{
    "setname": "HOU",
    "setlongname": "Hour of Devastation",
    "blockname": "Amonkhet",
    "setsize": 199,
    "setreleasedate": "2017-07-14",
    "settype": "expansion",
    "mtgsurl": "http://www.mtgsalvation.com/spoilers/183-hour-of-devastation",
    "mtgscardpath": "http://www.mtgsalvation.com/cards/hour-of-devastation/"
...
```

### PR DESCRIPTION
**Pull request by dev-id**
Refactor set_info to match mtgjson keys

Move download_images to wizards_scraper

Fixes #39 
Assists #95

### CODE REVIEW

**Comment by tooomm** [comment]
>Move download_images to wizards_scraper

Hehe, found a leftover from #98?

<br>

Internally, we basically use json files and mtgjson formatting all the time?
The **yml input** and **xml output** are just additions?

**Comment by dev-id** [comment]
We use python dicts which map to json perfectly in all our uses.

We do use mtgjson keys, but there's some leftovers in mtgs scraper that use some different keys.

**Comment by tooomm** [comment]
>We do use mtgjson keys, but there's some leftovers in mtgs scraper that use some different keys.

Besides the ones you changed here?
https://github.com/Cockatrice/Magic-Spoiler/pull/104/files#diff-56330639fe863365e37a8175e77fbc27

**Comment by dev-id** [comment]
These: [(cost='', cmc='', img='', pow='', name='', rules='', type='',
  | color='', altname='', colorIdentity='', colorArray=[], colorIdentityArray=[], setnumber='', rarity='')](https://github.com/tritoch/Magic-Spoiler/blob/8ce20bd44643587657dc4e1c43db72331ad19691/mtgs_scraper.py#L53-L54)

**Pull request merged**
