### PR TITLE
more future sets info

### PR DESCRIPTION
**Pull request by tooomm**
Not all set information available that early for sure.
Cut back on debug log for sets without any spoiled cards.
This PR also extends the in-file documentation a bit.

Sources:
- http://www.mtgsalvation.com/forums/magic-fundamentals/the-rumor-mill/673776-schedule-of-upcoming-releases-and-spoiler-seasons
- http://magic.wizards.com/en/products/iconic-masters
- http://markrosewater.tumblr.com/post/163779974563/wait-so-the-unstable-set-code-is-ust-i-thought
- http://magic.wizards.com/en/products/rivals-ixalan
- http://magic.wizards.com/en/products/masters-25
- http://magic.wizards.com/en/products/dominaria
- http://magic.wizards.com/en/products/core-2019

### CODE REVIEW

**Comment by tooomm** [comment]
before your change: https://travis-ci.org/Cockatrice/Magic-Spoiler/builds/272653676#L500-L531
```
XML Stats for XLN
Total cards: 126
Newest: Spell Pierce
Runtime: 20:57 (UTC) on 2017-09-06
XML Stats for IMA
Total cards: 0
Newest: 
Runtime: 20:57 (UTC) on 2017-09-06
XML Stats for UST
Total cards: 0
Newest: 
Runtime: 20:57 (UTC) on 2017-09-06
XML Stats for RIX
Total cards: 0
Newest: 
Runtime: 20:57 (UTC) on 2017-09-06
XML Stats for A25
Total cards: 0
Newest: 
Runtime: 20:57 (UTC) on 2017-09-06
XML Stats for DOM
Total cards: 0
Newest: 
Runtime: 20:57 (UTC) on 2017-09-06
XML Stats for M19
Total cards: 0
Newest: 
Runtime: 20:57 (UTC) on 2017-09-06
XML COMBINED STATS
Total cards: 126
Newest: Spell Pierce
Runtime: 20:57 (UTC) on 2017-09-06
```

---

after your change: https://travis-ci.org/Cockatrice/Magic-Spoiler/builds/272668101#L500-L507
```
XML Stats for XLN
Total cards: 126
Newest: Spell Pierce
Runtime: 21:44 (UTC) on 2017-09-06
XML COMBINED STATS
Total cards: 126
Newest: Spell Pierce
Runtime: 21:44 (UTC) on 2017-09-06
```

So empty sets are skipped without mention, debug wise I think it might be better to list them at least.
So that we know they are there and correctly entered+recognized. What do you think @dev-id?
`Skipping entered sets with no spoiler data found: set1, set 2...`
`Skipping entered sets with no spoiler data available: set1, set 2...`
`Skipping entered sets without spoiler data: set1, set 2...` or any other suitable phrase :)

**Comment by tooomm** [comment]
Maybe not perfect, but way better in total. I like it 👍

**Comment by dev-id** [comment]
Because of the way the function runs, creating a combined print line is cumbersome. Each set gets one line for now.

**Comment by tooomm** [comment]
Which is totally fine for now. When I looked at the function I figured that...
Have a look at gitter, in case you don't plan on any further changes here, we can time the merge just before our cron runs to see if the changes to empty outputs are working. ;)

Haha, too fast. Or I was too slow, damn it.

**Pull request merged**
