### PR TITLE
Scryfall log cleanup

### PR DESCRIPTION
**Pull request by dev-id**
Less lines per log - Scryfall comparison off by default, manual cards print on one line.

### CODE REVIEW

**Comment by tooomm** [comment]
manual cards are printed like this now:
>Manual Cards Added: u'Taigam, Ojutai Master', u'Ramos, Dragon Engine', u'O-Kagachi, Vengeful Kami', u'The Ur-Dragon', u'Wasitora, Nekoru Queen'

https://travis-ci.org/Cockatrice/Magic-Spoiler/builds/246208938#L394

What's the `u` about?

**Comment by dev-id** [comment]
Unicode

**Comment by tooomm** [comment]
we can do the same for split cards: https://travis-ci.org/Cockatrice/Magic-Spoiler/builds/246208938#L374-L377

**Comment by dev-id** [comment]
Keeping split as-is, easier to see those getting picked up and not too numerous currently

**Pull request merged**
