### PR TITLE
[WIP] Don't build .md-only changes on Travis

### PR DESCRIPTION
**Pull request by dev-id**

### CODE REVIEW

**Comment by dev-id** [comment]
Currently would fail a build with only `.md` changes.

**Comment by tooomm** [comment]
Where did you read about that undocumented command? :D

**Comment by dev-id** [comment]
Travis support

**Comment by tooomm** [comment]
TODO:
- [ ] move the `preflight.sh` file to `.travis` folder
- [ ] update the path of it in `travis.yml` accordingly
- [ ] merge the new master back in this PR

**Pull request closed without merging**
