### PR TITLE
update github action

### LINKED ISSUE #129: prevent date-only changes to spoiler files
Just let travis push changes (especially date-only updates!) when there is a change to the file besides the date.

It's confusing if the date updates, but not the content. A reddit user might try to update/override the file over and over again without seeing any actual changes/new content!
Also messes around with the activity feed in gitter during off-season, as well as repo activity on github in general!

Maybe we can check if some of the `setcode.xml` files are changed as well.
Because the `spoiler.xml` file reflects that changes, plus the date change. Without a change in the single e.g. `HOU.xml` (or any other single set xml or json file), there should never be a need for a change in `spoiler.xml`.
Or check for changes in that particular [line](https://github.com/Cockatrice/Magic-Spoiler/blob/files/spoiler.xml#L3) for example, since that line reference is always the same...

There might be an even smarter way of handling this?!

### PR DESCRIPTION
**Pull request by ebbit1q**
use the node-16 version of checkout
replace use of set-output with adding to GITHUB_OUTPUT
fix xml comparison using the info tags
fix deploy being triggered while only date has changed
fixes #129

### CODE REVIEW

**Comment by ebbit1q** [comment]
oh, I also trimmed the installed requirements, I have no idea what the requirements.txt is for but only three libraries are used by the updater

**Comment by ebbit1q** [comment]
this saves 7 seconds

**Comment by tooomm** [comment]
I can't comment on the code itself, but you are definitely addressing some issues.

Are you saying the requirements file contains no longer needed dependencies?
Maybe you can try to generate an updated version with e.g. https://github.com/bndr/pipreqs.

**Comment by ebbit1q** [comment]
the requirements.txt have so many other libraries it makes me think they are for something else I don't know about.

**Pull request merged**
