### PR TITLE
refactor loading json

### PR DESCRIPTION
**Pull request by leematos**
Hey all! Looking to start contributing and this section jumped out as ripe for a quick refactor. I don't love the structure now, but it's cleaner than it was and more DRY. :)

### CODE REVIEW

**Comment by leematos** [comment]
It also looks like verify_files.py could be refactored based on this as well? I'm not sure what the end game is for that file.

**Comment by leematos** [comment]
I see that verify files is for CI. _continues to explore the project_

**Comment by tooomm** [comment]
Yes, verify_files.py was split out from main.py (atm somehow duplicated) to let travis check the files before actually initializing and running the script (wasting a lot of time) just to tell a contributor in a pr that they did an invalid change or forgot a comma in the corrections file.

https://github.com/Cockatrice/Magic-Spoiler/issues/52 --> https://github.com/Cockatrice/Magic-Spoiler/pull/64

**Comment by dev-id** [comment]
main.py should call verify_files.py that would be better.

**Pull request merged**
